mirage/ocaml-git

lib/unix/git_unix.ml

On a system where TMPDIR is on its own partition, `Lwt_unix.rename`
will fail with `Unix.EXDEV` (can't rename over different filesystems).
This puts the temp file in the same directory as the target file.
Looks like a side-effect of 94701e6

Override TMPDIR for Git_unix.write_file

---

lib/sync.ml

I've been testing this on bitbucket.org, but it (understandably) doesn't speak git unless the user-agent contains at least "git/".

Add User-Agent: ogit/$version header to smart HTTP

---

bin/ogit.ml
lib/FS.ml
lib/SHA.ml
lib/SHA.mli
lib/pack.ml
lib/pack.mli
lib/pack_index.ml
lib/pack_index.mli
lib/packed_value.ml
lib/packed_value.mli
lib/tree.ml
lib/tree.mli

I have modified the original to achieve the following:
* to allow short SHA1s for specifying Git objects, and 
* to mimic git-ls-tree and git-cat-file.
The latter is implemented based on binary search for a SHA1 within an index file, as seen in Git.
The patches could be better by catching up with the evolution of the original; The actual modifications have been performed several months ago...

Modified to allow abbreviated SHA1 and to mimic git-ls-tree and git-cat-file

---

lib/http/git_http.ml
lib/http/git_http.mli
lib/mirage/git_mirage.ml
lib/unix/git_unix.ml

This is just quick fix in case you want to make a release that unbreaks
everyone.
@samoht I'm just curious, why does ocaml-git need such low level access to
cohttp internals anyway? I would like to understand the use case.

Cohttp 0.18.0 compatibility

---

lib/mirage/git_mirage.ml
lib/mirage/git_mirage.mli
lib/sync.mli

Judging by git_mirage.ml and the channel API it calls, "bytes" is meant here rather than "bits".

s/bits/bytes/ in docstring for read_exactly

---

lib/http/git_http.ml
lib/http/git_http.mli
lib/mirage/git_mirage.ml
lib/unix/git_unix.ml

* I've simplified the definition of CLIENT. I'm not sure why it needs
Cohttp_lwt.Client at all if it's doing request/response processing by
itself :)
* write_footer has been added here because it shouldn't be part of
cohttp's api.

Compatibilty with cohttp 0.19.1

---

lib/pack.ml
lib/packed_value.ml
lib/packed_value.mli

Use D.string instead.  See #129.

Remove the obsolete ~digest argument to to_pic.

---

lib/FS.ml
lib/SHA.ml
lib/blob.ml
lib/commit.ml
lib/global_graph.ml
lib/index.ml
lib/memory.ml
lib/misc.ml
lib/misc.mli
lib/object_type.ml
lib/pack.ml
lib/pack_index.ml
lib/packed_value.ml
lib/reference.ml
lib/sync.ml
lib/tag.ml
lib/tree.ml
lib/user.ml
lib/value.ml

Here's a typical piece of logging code with a simple performance problem:
```ocaml
Log.debug "received %s (%s)" (pretty k) (pretty v)
```
The problem is as follows: even if debug printing is turned off, the (possibly-expensive) function `pretty` is still called, although its output is discarded.
There are various approaches to avoiding the call to `pretty`, including
* syntax extensions (as in [Bolt](http://bolt.x9c.fr/)): we might introduce new syntax using Camlp4 that expands into code that is not executed when the logging level is too low:
```ocaml
LOG "received %s (%s)" (pretty k) (pretty v) LEVEL DEBUG;
```
* a lazy wrapper around the logging call which is only forced when the logging level is sufficiently high
```ocaml
Log.debug_force
(lazy 
(Log.debug "received %s (%s)" (pretty k) …
```

Improve logging performance: only build arguments when needed

---

lib/FS.mli
lib/unix/git_unix.ml

Otherwise, they don't get closed until GC time and we may fail with `ENFILE` or `EMFILE`.

Read files rather than mmapping them

---

lib/unix/git_unix.ml

Reading a 100 MB pack file went from 0.40s to 0.06s (there's still too much copying though - Python reads the same file in 0.05s).

git-unix: use larger buffer for large files

---

lib/unix/git_unix.ml

Use of mmap is necessary to handle packfiles efficiently. Since these
are stored in a weak map, we won't run out of open files if we keep
accessing the same one.
Using read is necessary to handle references, since these are mutable
and can't be cached. Using mmap here leads to hitting the OS limit on
the number of open files.

Use mmap for large files and read for small ones

---

lib/FS.ml
lib/memory.ml
lib/pack.ml
lib/pack.mli
lib/packed_value.ml
lib/packed_value.mli
lib/store.mli

Before, the only way to get the size of a file was to decompress the whole thing.
The main win comes from getting the size of raw packed objects without decompressing. There are a couple of further improvements possible:
- Calculate the size of loose objects without loading them.
- For deltas in packs, only decompress the first few bytes (to get `result_size`).
This reduces the time to scan a large tree from 35s to 30s on my test repository. It's not a huge improvement, but probably the right thing to do. Still trying to work out what takes the rest of the time. For reference, Git manages to decompress and check out all the files into the working tree in 4.9s :-/

Add Store.size

---

lib/unix/git_unix.ml

On some use case with a huge repository, this was seriously too slow. It was completely GC bound (doing lots of compactions).
This bring it back to reasonable performances.

Less unefficient Git_unix.read_file_with_read

---

lib/git.mli
lib/git_fs.ml
lib/git_pack.ml
lib/git_pack.mli
lib/git_packed_value.ml
lib/git_packed_value.mli

This speeds-up reads in a big pack file. Related to docker/datakit#287
On one example where where I have 2 pack files and:
```
$ du -h .git/objects/pack/
592M    .git/objects/pack/
```
the full application start-time passed from:
```
real    3m41.018s
user    0m2.101s
sys     0m1.614s
```
to
```
real    0m46.003s
user    0m1.566s
sys     0m1.284s
```

Cache more files in the filesystem when reading a pack file

---

lib/git_crc32.ml

Fix CRC32 initialisation and finalisation

---

.merlin
.travis.yml
Makefile
_tags
appveyor.yml
git-http.opam
git-mirage.opam
git-unix.opam
pkg/pkg.ml
src-mirage/git_mirage.ml
src-mirage/git_mirage.mli
src-unix/git_unix.ml
src-unix/ogit.ml
src/git.mli
src/git_fs.ml
src/git_fs.mli
src/git_memory.ml
src/git_store.ml
test/test.ml
test/test_common.ml
test/test_fs.ml
test/test_memory.ml
test/test_mirage.ml
test/test_store.ml

Also remove over-specifice realpath/getcwd functions from the signature. This
should be implemented by the unix tools, not by the library.

Add IO.test_and_set for FS implementations

---

appveyor.yml
src-mirage/git_mirage.ml
src/git_fs.ml
test/test_mirage.ml
test/test_store.ml

This involves:
- running the tests in the CI
- rewriting the references to be valid windows path (the issue was mentioned by @talex5 but I can't find where anymore)
- fixing the glue scripts to init MirageOS tests (this should probably be moved somewhere else, possibly in `mirage-fs-unix`)

Better windows support

---

src-unix/git_unix.ml

It seems that unlink can also raise EACCES on Windows (see
https://msdn.microsoft.com/en-us/library/5814770t.aspx)
Also, the current exponential backoff for writing files was lacking
intermediate steps, which would make some write very slow.

unix: more fixes for the Git_fs.IO on Windows

---

git-mirage.opam
git-unix.opam
git.opam
src/git-http/jbuild
src/git-unix/git_unix.ml
src/git-unix/jbuild
src/git/git.mli
src/git/inflate.ml
src/git/inflate.mli
src/git/jbuild
test/common/jbuild
test/git-mirage/test.ml
test/git/test.ml

Better implementation of `inflate`/`deflate` function. We allocate only one time the needed buffer (`input` and `output`) used to `inflate` __and__ `deflate`.  Because these functions is used in a _stop the world_ context, it's safe to use the same global buffer - otherwise, it's needed to have these buffer per serialization/deserialization contexts (and it's this case in `sirodepac`).

Decompress (follow #210)

---

index.html

I'm not sure if you have removed this index accidentally or on purpose, but now the link to the API from the README file is broken. Also, "up" navigation from git-unix/index.html and other pages is broken too.
So I've restored a part of the old index file (removed the part that links to the other removed indexes, like modules index, etc..). You may want to add it some style.

Restore top level index

---

CHANGES.md
appveyor.yml
git-http.opam
git-mirage.opam
git-unix.opam
src/git-http/jbuild
src/git-mirage/jbuild
src/git-unix/jbuild

This needs https://github.com/mirage/ocaml-conduit/pull/232 to link the tests properly

Update to conduit.1.0 and cohttp.0.99

---

src/git/jbuild

this used to work since cstruct used to require ocplib-endian, see https://github.com/mirage/ocaml-cstruct/pull/177

add ocplib-endian to dependencies of git (already in opam, missing in jbuild)

---

src/git/store.ml

The fix is about the ownership needed by the PACK algorithm. In fact, as the documentation said (and as I know), the PACK algorithm expect to take the ownership of any `Cstruct.t` provided by the `get` function. In other side, if we don't respect this, the `Cstruct.t` will be corrupt by some others processes and change the result of the delta-ification.
This fix just take care about which `Cstruct.t` need to be copied.
Ready for merging.

Fixed bug about ownership of cstruct when we canonicalize received PACK file

---

.travis.yml
appveyor.yml
git.opam

The only remaining one (on both Linux and Windows) is `angstrom`.
Note the tests are still failing on Windows, I am planning to investigate these this week.

Remove unnecessary pins in CI scripts

---

src/git/reference.ml

When we get the end of the file (when the _syscall_ `read` returns `0`), we notice the decoder than the stream is finish.

Fixed infinite loop in the reference decoder

---

.travis.yml
CHANGES.md
appveyor.yml
git-http.opam
git-mirage.opam
src/git-http/git_http.ml
src/git-http/git_http.mli
src/git-mirage/git_mirage.ml
src/git-mirage/jbuild
src/git-unix/git_unix.ml

This needs https://github.com/mirage/ocaml-cohttp/pull/594 to be merged and released first.

Update to latest cohttp versions

---

src/git/collector.ml
src/git/revision.ml
src/git/tree.ml
src/git/tree.mli

This PR is a merge of #252 and #253 plus a fix about the PACK file.
Again it's about the ownership of the `Cstruct.t` send to the PACK algorithm. Then, this function take care to not delta-ify multiple times the same object. About the last change, may be it's more useful to expect from the client a `Set` of objects instead a list.

Bug to generate a PACK file

---

src/git/mem.ml
src/git/minimal.ml
src/git/store.ml
src/git/store.mli

Add a new `buffer` type which and add a few buffers to Git repositories' state.
Add a few convenience functions to allow sharing these buffers via an Lwt_pool.
The concurrent behavior of all these functions should now be clearer and safer.

Remove _p and _s functions

---

src/git-mirage/fs.ml
src/git-mirage/fs.mli
src/git-mirage/git_mirage.ml
src/git-mirage/git_mirage.mli
src/git-unix/fs.ml
src/git-unix/fs.mli
src/git-unix/git_unix.ml
src/git-unix/git_unix.mli
src/git/helper.ml
src/git/helper.mli
src/git/index.ml
src/git/loose.ml
src/git/mem.mli
src/git/minimal.ml
src/git/pack_engine.ml
src/git/packed_refs.ml
src/git/reference.ml
src/git/reference.mli
src/git/s.ml
src/git/store.ml
src/git/store.mli
src/git/unpack.ml
test/common/test_store.ml
test/common/test_sync.ml
test/git-mirage/test.ml
test/git-unix/test.ml
test/git/test.ml

This allows to remove the 'GAMMA' functor parameter and to cleanup the
`create/connect` functions. Now the main store signatures do not define a
creator anymore, only the implementation do and they can take different
parameters (e.g. the typical MirageOS style).

Weave in the file-system state in every filesystem calls

---

.travis.yml
appveyor.yml
git-mirage.opam
git.opam
src/git/helper.ml

Update `ocaml-git` to the last API of `angstrom`.

Fix angstrom

---

src/git/helper.ml
src/git/helper.mli
src/git/loose.ml
src/git/packed_refs.ml
src/git/reference.ml

This PR is a step to abstract step by step file-system and limit POSIX syscall on the git core library. Currently, the status is to use `to_file` and `of_file` which use a subset of POSIX syscall (and can be easily translated to another back-end like [wodan](https://github.com/g2p/wodan)) to load or store a Git object (loose or reference) from a file-system.
However, this abstraction is provided by the `Helper` module which stills on the Git core library.
Then, pack-engine stills to use POSIX syscall in only one place (`Pack_engine`) to do a first pass but an update of the pack-engine is out of the scope of this PR - and compatibility between `wodan` and the pack-engine stills an open question.

Abstract file-system

---

git-mirage.opam
git-unix.opam
git.opam
src/git-unix/git_unix.ml
src/git/fs.ml
src/git/git.mli
src/git/packed_refs.ml
src/git/packed_refs.mli
src/git/reference.ml
src/git/reference.mli
test/git-mirage/jbuild
test/git-unix/jbuild
test/git/jbuild

As ocaml-git 1.11 never unpack the packed references (instead it just writes
loose references when it wants to update them), test_and_set_reference needs
to be adapted.
Note: remove_reference and test_and_set ~set:None are completely buggy when
using packed references. This will be fixed by ocaml-git 2.0 but there is
no easy fix in ocaml-git 1.11... So simply add a note in API docs.

Fix test-and-set for packed references

---

src/git-unix/index.ml
src/git-unix/ogit-write-tree/main.ml
src/git/mem.ml
src/git/tree.ml
src/git/tree.mli
test/common/test_store.ml

This allows to check that steps are well-formed only once; add also convenient
fonctions to efficiently add/remove entries in a tree.

Make Tree.entry a private type

---

.gitignore
src/git/index_pack.ml
src/git/index_pack.mli
src/git/mem.ml
src/git/minimal.ml
src/git/pack_engine.ml
src/git/pack_info.ml
src/git/store.ml
src/git/store.mli
src/git/sync.mli
src/git/unpack.ml
src/git/unpack.mli
test/common/test_rev_list.ml

So this PR is a start to fix #286 and:
* Have a pack-engine which can be used in a context server or as a client
* Let the user to handle allocation
Firstly, we change a little bit the unpack module to be more general than before. The biggest change is to use an ADT to use a string or noticed `Cstruct.t` by the user instead to allocate some `Cstruct.t` (of 127 bytes) when the user did not noticed a already allocated `Cstruct.t`.
This `Cstruct.t`/`string` is used to store insert hunks while we delta-ify an object - and keep them at each level of delta-ification to apply them then at the end of the recursion. In _sirodepac_, I already noticed than `string` is not the best buffer to store them (specially when we wants to extract all objects of a PACK file, the OCaml GC does not support the …

New pack engine

---

src/git/pack_engine.ml

Fix compilation and replace Rabin by Duff in Pack_engine module

---

src/git/hash.ml
src/git/reference.ml

ocaml-git isn't building due to `eq` being renamed to `equal`.  This can also be observed in the CI logs for irmin: https://github.com/mirage/irmin/pull/552.
Feel free to close this if it's already being dealt with!

Replace eq with equal

---

src/git-mirage/dune
src/git-unix/dune
src/git-unix/ogit-cat-file/dune
src/git-unix/ogit-dot/dune
src/git-unix/ogit-http-clone/dune
src/git-unix/ogit-http-fetch-all/dune
src/git-unix/ogit-http-fetch/dune
src/git-unix/ogit-http-ls/dune
src/git-unix/ogit-write-tree/dune

This PR is like a PR out of box but from an other project which want to link with `irmin-unix` and `irmin-mirage`, it wants to link with `git-unix` and `git-mirage` by transitivity. However, both compiles with `digestif.c` & `digestif.ocaml` (`git-unix`) and `checkseum.c` & `checkseum.ocaml` (`git-mirage`). By this way, we link both implementations.
At the end, we did not retrieve any compiler errors (which is an issue?) but get a _segfault_. This PR should fix this problem.

Remove digestif.{c,ocaml}, checkseum.{c,ocaml} dependencies on git-unix and git-mirage libraries

---

test/common/test_store.ml

Check order on tree with of_list/to_list and add operation

---

git-http.opam
git-mirage.opam
git-unix.opam
git.opam

This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.

opam: remove the 'build' directive on dune dependency

---

src/git-unix/index.ml

/cc @kit-ty-kate
Git used into CI still uses INDEX file in version 2. Currently, this version is not properly tested when the current version of the INDEX file is 4. However, to avoid trouble in CI, I did a kind of fix.

Fix bug about padding needed for an index file (version 2)

---

git-http.opam
git-mirage.opam
git-unix.opam
git.opam
test/common/dune
test/common/test_store.ml
test/git-mirage/dune
test/git-mirage/test.ml
test/git-unix/dune
test/git-unix/test.ml
test/git/dune
test/git/test.ml
test/smart/dune
test/smart/test_smart.ml

since mirage-crypto requires OCaml 4.07.0, raise these here as well. also, get rid of custom reseeding code and Mirage_random_test.

use mirage-crypto instead of nocrypto

---

.ocamlformat
git-mirage.opam
src/git/store.ml
test/git-mirage/dune
test/git-mirage/test.ml

This PR wants to enlarge internal buffers to be able to decode large tree object as noticed here: mirage/irmin#1001. The PR deletes an old french comment about a possible bug because we used `set_len`/`add_len` (see mirage/ocaml-git#345).
It's a small fix (and highlight a larger problem) but something better will appear soon (so much teasing).

Enlarge internal buffers to be able to parse large tree objects

---

src/git/hash.ml
src/git/hash.mli

This type does not need to be constraint where nobody really use it. In other side, mirage/digestif#103 was merge and we will have an incompatibility.

Delete useless constraint on Hash.kind type

---

src/git-unix/git_unix.ml
src/git/mem.ml
src/git/sync.ml
src/git/sync.mli
src/not-so-smart/fetch.ml
src/not-so-smart/fetch.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git.mli

Adds progress reporting capability (as arguments) to fetch through all fetch "levels":
`Nss.Fetch.fetch_v1 <- Smart_git.fetch <- Sync.fetch <- Git_unix/Mem.fetch`

add progress reporting capability to fetch

---

src/git/cstruct_append.ml
src/git/git.ml
src/git/git.mli
test/cstruct_append/dune
test/cstruct_append/test.ml

`assert` saved me but I need to implement a proper test about that. `Cstruct_append` is exposed, let's start to play with ephemerons.

Fix mis-write of k* into Cstruct_append

---

src/git-unix/git_unix.ml
src/git/mem.ml
src/git/sync.ml
src/git/sync.mli
src/not-so-smart/fetch.ml
src/not-so-smart/protocol.mli
src/not-so-smart/smart.mli
test/smart/dune
test/smart/test.ml
test/smart/uid.mli

- moves repetitive fetching from `Git_unix.fetch` and `Mem.fetch` to `Sync.fetch`
- changes `Sync.fetch` behavior to save fetched ref `src` either as `dst` ref if provided by the user or as `src`

Fix Sync.fetch behavior to save not only local refs

---

src/carton/idx.ml

Spotted by @ulugbekna, I need to implement some tests.

Fix the ephemeron used to simulate and temporary device for the memory back-end of Git

---

src/git-unix/ogit-fetch/main.ml
src/not-so-smart/decoder.ml

Changes are in modules that I am working on now. Left `==` uses in `carton` et al. unchanged.

replace '==' with '=' in 'nss/decoder' and 'ogit-fetch'

---

src/not-so-smart/default.ml
src/not-so-smart/fetch.ml
src/not-so-smart/fetch.mli
src/not-so-smart/smart_git.ml

Previously, we called a prelude the message sent from the client to server requesting a service. Such a request message is necessary only for `git://` transport, so the code should be more understandable if we give it a more explicit name. 
A note: 
@dinosaure 's comment in the code
```ocaml
(* XXX(dinosaure): [prelude] is the only tweak needed between git:// and SSH. *)
```
in reality means that `prelude` is the only tweak needed between `git://` and (SSH and `file://`), but since we don't support `file://`, the comment is true. Also note that `http://` is quite different from all other transports and is not considered in this context of initial request of service from server.

Replace 'prelude' with 'uses_git_transport'

---

src/git/sync.mli
src/not-so-smart/decoder.ml
src/not-so-smart/decoder.mli
src/not-so-smart/dune
src/not-so-smart/fetch.ml
src/not-so-smart/protocol.ml
src/not-so-smart/protocol.mli
src/not-so-smart/smart.ml
src/not-so-smart/state.ml
src/not-so-smart/state.mli

- added some docs
- moved `nss/decoder.ml/i` and `nss/encoder.ml/i` to `git-nss.pkt-line` lib to be able to re-use it in wire protocol v2
- made some refactorings (would appreciate your comment if I'm using `Bytes.unsafe_of_string` correctly)
- there are a couple of functions that are defined but not used, which I could remove, but that's up to you
- I can also revert some commits if you don't like them

Small refactor decoder

---

carton-git.opam
carton.opam
git-nss.opam
git-unix.opam
git.opam

Follow #421 and constraint packages to use, at least, `fmt.0.8.7` (which added the deprecation).

Constraint to use, at least, fmt.0.8.7

---

src/git-mirage/git_mirage.ml
src/git-mirage/git_mirage.mli
src/git-mirage/git_mirage_ssh.ml
src/git-mirage/git_mirage_ssh.mli
src/git-unix/git_unix.ml
src/git/mem.ml
src/git/sync.ml
src/git/sync.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git.mli
unikernel/unikernel.ml

No regression here, I tested the unikernel locally and even if the user gives to use an SSH key with a GRI remote, we start a GRI (with the prelude) connection. /cc @ulugbekna

Delete the useless verify function and start an SSH connection with a pre-condition over the given Smart_git.Endpoint.t

---

.travis.yml
appveyor.yml
src/git-mirage/git_mirage_dns.ml
src/git-unix/ogit-fetch/main.ml
src/not-so-smart/dune
src/not-so-smart/fetch.mli
src/not-so-smart/protocol.ml
src/not-so-smart/protocol.mli
src/not-so-smart/push.mli
src/not-so-smart/smart.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git.mli
test/smart/dune
test/smart/test.ml
test/smart/test_edn.ml
unikernel/config.ml
unikernel/unikernel.ml

A minor patch (followed by a release) to be able to gives to an unikernel something like: `git@[10.0.0.1]:path` (mostly when we want to start a primary DNS server.

Handle IPv4 when the user gives git@[IPv4]:path as the remote

---

test/index/test.ml
test/smart/test.ml

The tests of git-unix fail if there's no global `.gitconfig` setting
user.name and user.email in every `git commit` being run. This easily
fixed by setting a local git config per repository/store used.
This fixes the tests failing in sandboxed environments or on systems
without git set up properly.

git-unix: make index and regression test work without global gitconfig

---

src/git-mirage/git_mirage.ml
src/git-mirage/git_mirage_ssh.ml
src/git-mirage/git_mirage_ssh.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git_intf.ml
unikernel/config.ml

This PR should fix the problem to make 2 ctx depending on what we want:
- if we want to fetch
- if we want to push
Now, `Sync.fetch`/`Sync.push` will automatically fill the given ctx with such information needed by `Git_mirage_ssh` (to be able to call `git-receive-pack`/`git-upload-pack`). /cc @hannesm (no need to upgrade `irmin`)

Fill automatically the context with read/write capabilities depending on what the user want

---

unikernel/config.ml

Discover by @hannesm and me, the `mimic_git_conf` should not take an empty `Mimic.ctx`.

mimic_git_conf must take properly the ctx given as the second argument

---

test/smart/test.ml

The issue fixed here is the same as #439. We also make sure the git
config is set in make_one_commit in case tests are run in an environment
without a global git config.

git-unix: Fix new smart test without a global git config

---

src/not-so-smart/find_common.ml

- make semantically close things closer in file
- removed underscores from variable names because they usually
mean values are not used, which is not the case here
- use a first-class module to remove rebinding scheduler
functionality again and again

ref-find-common

---

git.opam
src/git/commit.ml
src/not-so-smart/decoder.mli
src/not-so-smart/dune
src/not-so-smart/protocol.ml
src/not-so-smart/push.ml
src/not-so-smart/smart.ml
src/not-so-smart/smart.mli
src/not-so-smart/smart_git.ml

This PR has two things:
- fix a bug about commit
Indeed, we should have an extra-LF between the commit header and the message. I suspect that Git broke something about that and it silently accepts such commit without verification (`git log` deals with that). However, it seems that `git fsck` checks such assumption and when we want to push over HTTP on GitHub, this command is launched and invalidate our PACK file.
It's a breaking change! Due to the design of `ocaml-git`/`encore`, old commits (without the double LF) **are not** accepted anymore - we are surely more conservative than Git on this aspect... I advise (/cc @hannesm) to make a fake commit (`git commit --allow-empty -m.`) to sanitize, at least, the last commit (and properly do, then, the `git fetch --depth=1`).
For the story, I …

Implementation of HTTP push and fix bug about commit

---

src/git/commit.ml
src/git/commit.mli
src/git/tag.ml
src/git/tag.mli
test/smart/test.ml
test/test_store.ml
test/unix/dune
test/unix/test.ml

Fix mirage/irmin#917. A `git fsck` is launched to check some invariants about format of Git objects. Note that `cgit` silently accepts our commits for a long time without errors. This PR has a breaking change about the API. A patch on `irmin` will coming soon to keep the compatibility.

A git commit can have an empty message

---

test/unix/test.ml

This is becoming a similar sight, but easily fixed, updates in NixOS should be done soon as well :)
---
git commit fails if user.email and user.name are not set which may be
the case for sandboxed environments for example. This is easily fixed by
setting a local git config for the current directory before commiting.

test/unix: fix write test without a git config

---

carton-git.opam
carton-lwt.opam
carton.opam
git-unix.opam
git.opam
src/not-so-smart/decoder.ml
src/not-so-smart/decoder.mli
src/not-so-smart/protocol.ml
src/not-so-smart/protocol.mli
src/not-so-smart/push.ml
src/not-so-smart/smart.ml
src/not-so-smart/smart.mli
test/smart/loopback.ml
test/smart/test.ml

The current situation about `report-status` and protocols is a bit a mess. At this stage, I can say that with `Side_band_64k` and `Report_status` capabilities, all protocols works. I can say that `git://` works with any capabilities. However, SSH and HTTP(s) have some problems if we don't use these capabilities (even if we replace `Side_band_64k` by `Side_band`).
Because the protocol is completely under-documented, it's hard for me to understand where is the bug and reproducibility seems hard when the Git protocol involve along the versions.
However, this PR seems to fix problems for our use case (with `irmin`) and pass regression tests (thanks for the old version of me). Unikernels work with that and we are able to fetch/push correctly _without_ any problems.

A fix about reporting status when we push

---

.ocamlformat
src/carton-git/carton_git.ml
src/carton-git/carton_git.mli
src/carton-git/carton_git_unix.ml
src/carton-lwt/carton_lwt.mli
src/carton/thin.ml
src/carton/thin.mli
src/git-unix/git_unix.ml
src/git/cstruct_append.ml
src/git/mem.ml
src/git/store.ml
src/git/sync.ml
src/not-so-smart/pck.ml
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git_intf.ml
test/carton/test_lwt.ml
test/cstruct_append/test.ml
test/smart/append.ml

A spurious bug appears when I play with unikernels when ephemerons are deleted even if we did not yet finish the process. Such case appear when we fetch a _thin_ PACK where the process can be _long_ (from the POV of the GC). Two errors appears:
- first, we don't really keep alive ephemerons
- `O_TRUNC` is **not** expected at some points
The second point is the most important where a second open of the PACK file will delete the underlying `Cstruct.t` even if we just want to read it. So we upgrade interfaces (specially `carton`) to know if we really want to `O_TRUNC` or not. Another solution is to `O_TRUNC` only when we want to write (information given by the `mode` argument) - but I'm not sure about the `RdWr` case.
As far as I can tell, this patch fix the problem but we don't have a test …

Fix a bug about ephemeron/cstruct_append/O_TRUNC

---

src/git/tree.ml
src/git/value.ml

This PR fixes a possible stack overflow in `Tree.v` found when working with very wide trees in Irmin
See https://github.com/mirage/irmin/pull/1313

Fix possible stack overflow in Tree.v

---

src/git-top/dune
src/git-unix/dune
test/cstruct_append/dune
test/index/dune
test/mem/dune
test/unix/dune

This project uses `(implicit_transitive_deps false)`, but doesn't
specify all transitive deps in the case of these libraries. With the
main releases, this is OK since they don't build with Dune, but it's a
bug when using the Dune overlays / `opam monorepo` for development.

Add missing library depends on `fmt` and `logs`

---

test/carton/test.ml
test/cstruct_append/test.ml
test/smart/test.ml
test/unix/test.ml

Upgrade with `alcotest.1.4.0` and set the `tmp` directory to something which is in the same hard disk (we found some problems on the `opam-ci` about bad use of `rename`).

Be compatible with alcotest.1.4.0 and localize tmp directory in the same hard disk

---

src/mimic/mimic.ml
test/mimic/test.ml

A small patch with a test to ensure that we use the last value inserted in the given `Mimic.ctx`. It's useful when we want to redirect the user to another `Uri.t`, we "replace" old values by the new given `Uri.t`.

Ensure that we manipulate the last value in the given Mimic.ctx

---

git.opam
src/loose/loose.ml

Use the non-streamable API when the transactions are supposed to be atomic.
It uses this [pull request](https://github.com/mirage/decompress/pull/102) which should be accepted soon

Use Ns decompress in atomic get and add

---

bin/carton/index_pack.ml
bin/carton/verify_pack.ml

OCaml 4.13 added `Int64.max` and thus made theses two lines break.
In general I would encourage people to avoid opens when possible at makes it more likely to have code that breaks in this fashion.

carton: Add compatibility with OCaml 4.13

---

git-paf.opam
git-unix.opam
src/git-paf/git_paf.ml
src/git-unix/git_unix_mimic.ml

Until ocaml/opam-repository#19218, this PR will fail. But then, it will unlock the dependency graph to use `tls.0.14.0`.

Update to tls.0.14.0

---

git-mirage.opam
src/git-mirage/dune

while investigating reverse dependencies (via https://opam.ocaml.org/packages/mirage-protocols/) I encountered ocaml-git which does not use this package

drop unneeded mirage-protocols dependency

---

bin/guit/dune
test/smart/dune

There are a couple of places where the link with `logs` or `logs.fmt` was forgotten in 3.6.0. This breaks the package installation in my opam switch :/

Link with logs and logs.fmt

---

src/git/mem.ml
src/git/minimal.ml
src/git/store.ml

Following discussion in https://github.com/mirage/irmin/pull/1698.

git: provide a `Store.read_opt` function for finding potentially-absent objects

---

bin/guit/dune

Hi dear `ocaml-git` maintainers,
Following this PR (https://github.com/mirage/ocaml-git/pull/499), I added `fmt` as a dependency to `v` to make `opam monorepo` work with `ocaml-git.3.8.0` and `irmin` lock file.

Fix fmt deps for v.exe

---

carton-lwt.opam

since this only changes the opam dependency, the same could be done to the carton-lwt 0.4.4 release to opam-repository (i.e. no need for a new release).

carton-lwt.opam: remove bigarray-compat

---

bin/carton/dune
bin/fiber/dune
src/carton-git/dune
src/git-index/dune

Silences the alert proposed in ocaml/ocaml#11198, but this PR can be merged regardless.

Add missing dependencies on Unix

---

src/not-so-smart/smart_git.ml
test/smart/dune
test/smart/test_edn.ml

I found that I could not fetch the repo http://git.data.coop/halfd/new-website.git. With full debug logs I was able to gather that http://git.data.coop//halfd/new-website.git was requested instead, and gitea treats that as an error and returns 404.
This PR removes the extra leading slash and adds a test case.

Do not append a leading slash to path

---

bin/guit/fetch.ml
bin/guit/v.ml

`mtime.2.0.0` [`CHANGES.md`](https://github.com/dbuenzli/mtime/blob/master/CHANGES.md):
> Remove deprecated values `Mtime.s_to_*` and `Mtime.Span.to_*` floating points functions. Note that the implementation of `Mtime.Span.to_*` functions was broken if your span exceeded `Int64.max_int`. Thanks to Thomas Leonard for the report ([#46](https://github.com/dbuenzli/mtime/issues/46)).
The behaviour is broken if the provided span exceeds `Int64.max_int`, but since this comes only from `Mtime_clock.elapsed_ns` it's probably safe to assume we've not been running for a few centuries. Thus I just copied the implementation of the old `Mtime.to_us` function.

Fix breaking change from `mtime.2.0.0`

---

src/not-so-smart/fetch.ml
src/not-so-smart/fetch.mli
src/not-so-smart/protocol.ml
src/not-so-smart/protocol.mli
src/not-so-smart/smart.ml
src/not-so-smart/smart.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git_intf.ml

Already spotted into `multipart_form` but currently, the stream of the PACK file is not bound. The side effect is: `lwt` does not really do the concurrence between the receiving and the decoding and we need to limit how many chunks we can have into our stream. So we use `Lwt_stream.bounded_push`.
The final expectation is to give opportunities to some processes to run even if we started to decode the PACK file. Now, the decoding is highly bound to the receiver (the _socket_) which can block. That mostly means that, by transitivity, the decoder can block too and let opportunities to some other processes.

Try to bounds the stream between the receiver and the PACK decoder

---

test/smart/dune

Otherwise got:
File "_none_", line 1:
Alert ocaml_deprecated_auto_include:
OCaml's lib directory layout changed in 5.0. The unix subdirectory has been
automatically added to the search path, but you should add -I +unix to the
command-line to silence this alert (e.g. by adding unix to the list of
libraries in your dune file, or adding use_unix to your _tags file for
ocamlbuild, or using -package unix for ocamlfind).

Remove OCaml 5 warning

---

test/carton/test.ml
test/unix/test.ml

- `git index-path` now requires a '.idx' extension for the index file
- `git fsck` has stricter timezone parsing and caught a bug in date calculation in a test when the current timezone is negative
Fixes #617

Fix tests for git 2.41.0+

---

README.md

Example was using 'master', rather than 'main'.
It was previously giving the error:
```
utop # Lwt_main.run Lwt.Infix.(read "README.md" >|= pp Fmt.stdout) ;;
[DEBUG]Reading HEAD.
[DEBUG]146 packed-refs added.
[DEBUG]Resolve reference refs/heads/master.
[DEBUG]Reading refs/heads/master.
refs/heads/master not found- : unit = ()
'''
Also the Travis link in the Readme is linking to master. I didn't fix that since it doesn't seem to be in use ATM  and didn't know what you want to do with it e.g. delete it or change to display the status on another build service.

Fix example in README.md (wrong branch name.)

---

src/git/value.ml
src/git/value.mli
test/value/dune
test/value/test.ml

Address issue with `of_raw_with_header` assuming it could read until the end of a given buffer and add a new function, `length_with_header`, that clients can use to inspect length read.
I ran into this while working on testing `irmin-server`. Its protocol (de)serializes blobs in the middle of a buffer, which does not work when using an `irmin-git` store. I have verified that this patch (with appropriate changes in `irmin-git`) fixes the issue for us.

Fix raw parsing in middle of buffer

---

fuzz/smart.ml
src/not-so-smart/find_common.ml
src/not-so-smart/protocol.ml
src/not-so-smart/protocol.mli
src/not-so-smart/smart.ml
src/not-so-smart/smart.mli

Encoder for ACK

---

carton.opam
src/carton-lwt/carton_lwt.ml
src/carton-lwt/lwt_io.ml
src/git/mem.ml

/cc @hannesm: a probably solution to let the `opam-mirror` unikernel be available even if we try to clone.

Give a pause when we iter on the index file and when we decompress a PACK file

---

src/git-mirage/git_mirage_http.ml
src/git-mirage/git_mirage_ssh.ml

The issue I observed was a unikernel that restarted all the time, but its argument had an issue "wrong padding" was the output, but while there was a backtrace, there was no useful information. I tracked it back that git-mirage-ssh got a ssh private key where the padding was bad.
So, this PR does (a) prefix the output with slightly more information and (b) returns exit code 64 (as defined in Mirage_runtime.argument_error) -- this is crucial since albatross then won't restart such a unikernel (that will not be able to succeed a startup, since the error will persist until the command line argument is changed).

git-mirage: avoid failwith, use exit 64 (argument error)
