mirage/ocaml-git

lib_test/test_common.ml
lib_test/test_store.ml

Fix #84. I don't understant how this could have happened ...

Fix the compilation of tests

---

.merlin
CHANGES.md
bin/ogit.ml
lib/FS.ml
lib/global_graph.ml
lib/memory.ml
lib/mirage/git_mirage.ml
lib/pack.ml
lib/pack.mli
lib/packed_value.ml
lib/packed_value.mli
lib/search.ml
lib/sync.ml
lib/unix/git_unix.ml
lib/user.ml
lib_test/test_common.ml
lib_test/test_fs.ml
lib_test/test_mirage.ml
lib_test/test_store.ml
opam

This should fix the virtual memory leak. @AltGr can you test it to see if that's better? Thanks!

Fix the fd leak and few other bugfixes and cleanups

---

.travis.yml
CHANGES.md
bin/ogit.ml
lib/FS.ml
lib/FS.mli
lib/http/git_http.ml
lib/memory.ml
lib/sync.ml
lib/sync.mli
lib_test/test_fs.ml
lib_test/test_memory.ml
lib_test/test_store.ml

Trying to simplify the Sync API. The current API is confusing as the difference from `fetch` and `pull` isn't clear.

Better fetch

---

lib/unix/git_unix.ml

See https://github.com/ocsigen/lwt/issues/229
/cc @talex5

Fix memory leak in IO.rec_files

---

bin/ogit.ml

See https://github.com/ocsigen/lwt/pull/107

Lwt_unix.run is deprecated

---

.travis.yml
lib/mirage/git_mirage.ml
lib/mirage/git_mirage.mli
lib_test/test_mirage.ml

connect returns a value directly

---

.travis.yml
_tags
lib/mirage/git_mirage.ml
lib_test/test_mirage.ml

Adapt to the MirageOS 3 exceptionless api

---

lib/mirage/git_mirage.ml

Adapt git to the MirageOS CHANNEL exceptionless interface

---

.merlin
.travis.yml
Makefile
_tags
appveyor.yml
git-http.opam
git-mirage.opam
git-unix.opam
pkg/pkg.ml
test/test.ml
test/test_common.ml
test/test_fs.ml
test/test_memory.ml
test/test_mirage.ml
test/test_store.ml

The sync tests should be run on both backends before we can say the sync operations are "mature" enough (hint: this is not the case currently).

Split the tests into `git-unix` and `git-mirage`

---

src-http/git_http.mli
src-mirage/git_mirage.mli
src-unix/git_unix.mli
src/git_gri.mli
src/git_index.mli

This PR edits the API docs for some existing documentation, and adds a tiny bit more.

API docs edits

---

README.md

This PR polishes the README by removing old references to libraries.

README: Mention Mirage_fs_lwt; details

---

.gitignore
src/git-unix/ogit/ogit.ml

Re-add missing ogit binary

---

src/git/reference.ml
src/git/reference.mli

Add infix operator to make a reference

---

src/git/commit.ml

I really don't like this PR because it's a weird process from an unsafe C code which does not define a clear (E)BNF syntax about the commit object but this is what happen now. To be clear a commit can be finished by a `\n` or not. Semantically, it's the same purpose: the commit does not have a message.
You can check this _rule_ here: https://github.com/git/git/blob/master/commit.c#L89
However, under the hood, this little difference is huge because it changes the hash/identifier generated from the commit _raw data_. So we need to dissociate an empty message with a `\n` and an empty message without. I realized this case when I unpacked some PACK files from the linux repository (which has some empty commits).
Before this PR, the idea is to consider the last `\n` as a part of the message. …

Fixed bug on the special case when the commit does not terminate with a \n

---

src/git/collector.ml
src/git/revision.ml

This patch is just a little improvement in some parts of the code (but necessary to merge).

Locals improvements

---

src/git/commit.ml

Suit and final patch of #255.
This patch **is not** the final patch to handle correctly a commit but a patch to continue to keep the integrity with with commits which contain extra headers - I just discovered this now ... So it's need to merge but we need to make a deep work to handle exhaustively headers (like `encoding`) and extra headers.

Delete assert in the commit parsing and keep the integrity

---

src/git-http/sync.ml
src/git/negociator.ml
src/git/smart.ml

All is explained in the src/git-http/sync.ml comment to understand
what happen and how to fix it. It's much more about an unspecified
behaviour than a bug.
I will explain later about this PR, I need to sleep.

Fixed fetch command over the HTTP protocol.

---

src/git/tree.ml
src/git/tree.mli

Then, perm_of_string recognize a directory if you send to it "40000"
or "040000".

Add Tree.pp_entry, Tree.perm_of_string and Tree.string_of_perm

---

src/git-http/sync.ml
src/git-http/sync.mli
src/git/collector.ml
src/git/mem.ml
src/git/pack.ml
src/git/pack.mli
src/git/pack_engine.ml
src/git/pack_info.ml
src/git/radix.ml
src/git/radix.mli
src/git/store.ml
src/git/store.mli
src/git/sync.ml
src/git/unpack.ml
src/git/unpack.mli
test/common/test_store.ml

Avoid functor nightmare

---

src/git/commit.ml
src/git/commit.mli
src/git/tag.ml
test/common/test_store.ml

Fix commit

---

src/git/mem.ml
src/git/minimal.ml
src/git/store.ml
src/git/store.mli
src/git/traverse_bfs.ml

Add iter function on common interface

---

src/git/pack_engine.ml
src/git/pack_info.ml
src/git/store.ml
src/git/unpack.ml
src/git/unpack.mli

A PR to prepare to the new PR which will implement an ascendant walker of PACK file (and, btw, improve performances).

Second pass

---

src/git-unix/fs.ml

Also precise the function name when the error is a real one.

unix: be less verbose on expected Unix errors

---

src/git/sync.ml

Previously we were trying to do some computation from the unknown objects
advirtised by the server (although they were in the exclude set).
The patch ensure that we just skip these objects instead of failing to produce
a valid path.
The use-case where this could happen is:
1. call fetch_one
2. do some update
3. call update_and_set
In the later case, having only one branch locally would cause some issues
without this patch.

push: fix git push when servers has unknown references

---

src/git-unix/index.ml
src/git-unix/index.mli
src/git-unix/ogit-http-clone/main.ml
src/git-unix/ogit-write-tree/main.ml
test/git-unix/test.ml
test/git-unix/test_index.ml

`dune exec -- src/git-unix/ogit-http-clone.exe https://github.com/mirage/decompress` generates something close to `git clone https://github.com/mirage/decompress. Should not work on Windows (most probably about path ...).

Properly clone and generate INDEX file

---

.travis.yml
appveyor.yml
src/git/tree.ml

Fix a `Malicious file` exception on big files.

Commit for each entries when we parse a tree object

---

src/git-http/sync.ml

Use userinfo on push, fetch, ls in smart http protocol.

---

git-mirage.opam
git.opam
src/git-mirage/dune
src/git/dune
src/git/helper.ml

Remove Cstruct.add_len and deep unsafe behavior, use ke instead

---

src/git-http/dune

Fix https://github.com/mirage/irmin/pull/666#issuecomment-479131183

Remove dependency to sexplib

---

.travis.yml
appveyor.yml
src/git/deflate.ml
src/git/inflate.ml

Prepare release of `v2.1.0`, waiting to release `decompress.0.9.0`

Use lastest version of decompress

---

git-mirage.opam
src/git-mirage/dune
src/git-mirage/net.ml
test/git-mirage/dune
test/git-mirage/test.ml

CI won't succeed since some dependencies are still not released to opam-repository (but PRed) -- conduit / cohttp

adapt to mirageos 3.7.0 changes

---

git-cohttp-mirage.opam
git-cohttp-unix.opam
git-cohttp.opam
src/git-cohttp-mirage/dune
src/git-cohttp-mirage/git_cohttp_mirage.ml
src/git-cohttp-mirage/git_cohttp_mirage.mli
src/git-cohttp-unix/dune
src/git-cohttp-unix/git_cohttp_unix.ml
src/git-cohttp-unix/git_cohttp_unix.mli
src/git-cohttp/dune
src/git-cohttp/git_cohttp.ml
src/git-cohttp/git_cohttp.mli

implement ogit-http-fetch

---

git-mirage.opam
git-unix.opam

Remove pin-depends on awa

---

CHANGES.mimic.md
carton-git.opam
carton-lwt.opam
git-cohttp-mirage.opam
git-cohttp-unix.opam
git-cohttp.opam
git-mirage.opam
git-unix.opam
mimic.opam
test/cstruct_append/dune
test/mimic/dune
test/mimic/unixiz.ml

Minor fixes about the release of `mimic.0.0.1`.

Release mimic

---

CHANGES.md

Mini release to be able to parse an IPv4 from a given Git endpoint.

Prepare v3.1.0

---

src/git-unix/git_unix.ml
test/unix/test.ml

Fix internal paths of PACK objects (prepend byt dotgit twice)

---

test/unix/test.ml

It's not a part of the release but tests fail on Windows (again) ...

Fix git gc on Windows

---

src/not-so-smart/pck.ml
test/smart/test.ml

Fix when we try to push to an empty repository, update becomes create

---

src/git-mirage/git_mirage.ml
src/git-mirage/git_mirage_dns.ml
src/git-mirage/git_mirage_dns.mli
src/git-mirage/git_mirage_ssh.ml
src/git-mirage/git_mirage_ssh.mli
src/not-so-smart/smart_git.ml
src/not-so-smart/smart_git_intf.ml
unikernel/README.md
unikernel/config.ml
unikernel/unikernel.ml

Improve a bit the unikernel to test the first push.

Improve a bit the unikernel

---

test/smart/test.ml

/cc @ulugbekna can you test on your side this small patch?

Fix last test about push empty

---

test/smart/dune
test/smart/pipe.ml
test/smart/test.ml

* open 'Bos' for the whole test file
* couple nitpicky changes

clean tests and add pipe module

---

fuzz/smart.ml
src/not-so-smart/decoder.ml
src/not-so-smart/decoder.mli
src/not-so-smart/encoder.ml
src/not-so-smart/encoder.mli
src/not-so-smart/fetch.ml
src/not-so-smart/find_common.ml
src/not-so-smart/protocol.ml
src/not-so-smart/push.ml
src/not-so-smart/smart.ml
src/not-so-smart/smart.mli
src/not-so-smart/state.ml
src/not-so-smart/state.mli

A couple of changes that can go outside of wire-proto-v2 PR

Pre-wire-proto-v2 changes

---

bin/guit/dune
bin/guit/fetch.ml
bin/guit/v.ml
src/git-unix/git_unix.ml
src/git-unix/packed_refs.ml
test/guit/dune
test/guit/v.t

Don't try to reset HEAD if it already exists

---

src/carton/dec.ml
src/carton/dec.mli
src/git-unix/git_unix.ml
src/git-unix/git_unix.mli
test/carton/test.ml

Small tweaks to be able to make a `Mirage_kv.RO` from `carton`.

Provide Git_unix.ctx and sector_size on carton

---

src/mimic/dune
src/mimic/index.mld

Add an explanation about mimic

---

src/mimic/implicit.ml

Already tested into `conduit.3.0.0`.

Optimize a bit mimic when we want to project the same flow

---

src/carton/idx.ml
test/carton/test.ml
test/carton/uid.ml

Be able to manipulate huge PACK files

---

git-mirage.opam
src/git-mirage/dune
src/git-mirage/git_mirage_http.ml
src/git-mirage/git_mirage_http.mli
unikernel/empty-commit/config.ml
unikernel/simple-store/config.ml
unikernel/simple-store/unikernel.ml

/cc @hannesm and related to this comment: https://github.com/mirage/mirage/pull/1283#discussion_r797990313

Git_mirage_http expects an authenticator as Git_mirage_ssh to verify the remote Git repository

---

src/carton/idx.ml
src/carton/idx.mli
src/git/cstruct_append.ml

A possible fix for OCaml 5.0 and ephemerons.

Fix usage of ephemerons

---

.ocamlformat
bin/carton/get.ml
bin/carton/hxd_cmdliner.ml
bin/carton/index_pack.ml
bin/carton/verify_pack.ml
bin/guit/fetch.ml
bin/guit/v.ml
carton.opam
git-unix.opam
git.opam
scripts/github-proxy

- https://github.com/dinosaure/hxd/pull/12
- https://github.com/stedolan/crowbar/pull/64

Cmdliner.1.1.0

---

src/git-unix/git_unix.ml

Spotted by @patricoferris, it fixes the `Major.reset` and delete properly PACK files.

Fix the deletion of pack files

---

CHANGES.md

Include into the `CHANGES.md` some releases which include the #565 fix.

Prepare 3.7.1

---

src/git/sync.ml

Fix the push process with a copy of illegal shared bigarray

---

.ocamlformat
bin/guit/fetch.ml
git-unix.opam
src/git-unix/git_unix.ml
test/carton/test.ml

Upgrade ocamlformat

---

unikernel/empty-commit/config.ml
unikernel/empty-commit/unikernel.ml
unikernel/simple-store/config.ml
unikernel/simple-store/unikernel.ml

Update unikernels with MirageOS 4

---

src/git-mirage/git_mirage_http.ml

/cc @reynir. The format of the `http-authenticator` will change with this patch (the format will be the same as expected by `X509.Authenticator.of_string`). I added a more friendly error message to help the end-user. Fix #582

Explain when the argument used for the authenticator is malformed

---

src/carton/dec.ml
src/carton/dec.mli
src/carton/enc.ml
src/carton/enc.mli

These functions can be useful to assert some kind of PACK files.

Add few functions to introspect target when we encode and be able to construct objects with source

---

src/not-so-smart/smart_git.ml

Be explicit about the format of Smart_git.Endpoint.of_string

---

src/git/store.mli

I was browsing [the docs](https://ocaml.org/p/git/latest/doc/Git/Store/index.html) and thought I might contribute a bit of clarification as I am exploring the library.

Small typo fixes

---

src/git-mirage/git_mirage_http.ml

This way we can report a better error to the user.
Without this patch I get this error in git-kv/app/mgit.exe:
```
Fatal error: exception Invalid_argument("error fetching: Handshake got an error")
```
This error message is fairly unhelpful. The remote URL seems to be fine, my internet connection works fine. What is the actual error?!
With this patch:
```
Fatal error: exception Invalid_argument("error fetching: Handshake got an error: git-paf: The default generator is not yet initialized. \nTo initialize the RNG with a default generator, and set up entropy collection and periodic reseeding as a background task, do the following:\n  If you are using MirageOS, use the random device in config.ml: `let main = Mirage.main \"Unikernel.Main\" (random @-> job)`, and `let () = register …
```

git-mirage: keep error message around

---

git-mirage.opam
git-paf.opam
git-unix.opam
git.opam

if approved / merged, I'm happy to upstream this to the opam-repository

add x-maintenance-intent field to the opam file

---

git-mirage.opam
git-paf.opam
git-unix.opam
git.opam
src/git-mirage/dune
src/git-mirage/git_mirage_http.ml
src/git-mirage/git_mirage_http.mli
src/git-mirage/git_mirage_ssh.ml
src/git-mirage/git_mirage_ssh.mli
src/git-paf/dune
src/git-unix/dune
src/git-unix/git_unix_mimic.ml
test/smart/test.ml

use dune variants instead of functors
